
[local]
localhost ansible_connection=local

# ── Jenkins user (explicit)
# ansible-playbook -i inventory.ini deploy.yml -l jenkins_user
[jenkins_user]
localhost ansible_connection=local ansible_user=jenkins

# ── System user (shikhar)
# ansible-playbook -i inventory.ini deploy.yml -l shikhar_user
[shikhar_user]
localhost ansible_connection=local ansible_user=shikhar
